### PR TITLE
Read electron flags from ~/.config/electron-${version}-flags.conf

### PR DESCRIPTION
**Pull request by darkbasic**
Nowadays electron is basically unusable on Wayland unless you pass the `--ozone-platform-hint=auto` and `--enable-features=WaylandWindowDecorations` parameters (the last one on Gnome at least). Having to do so manually from the cmdline is a pain and while Chromium has `/etc/default/chromium` there is no such thing for electron. It's so annoying that Arch Linux started shipping a wrapper which does exactly that: reads `~/.config/electron-${version}-flags.conf` and automatically passes the parameters it reads. This PR mimics the same exact approach. First of all I had to modify eselect-electron, which I discovered was completely broken: `ln -sf` doesn't exit with an error code if it tries to symlink to a non existent path and symlinking all possible paths (`/usr/lib{,32,64}`) ended up working just because `lib64` is usually the last one (not sure if it worked on 32 bit systems though). Now I check for existence before trying to symlink and I symlink `/usr/bin/electron` to `/usr/bin/electron-${version}` instead of `/usr/${libdir}/electron-${version}/electron`: this is because we always want to use the wrapper. Then I patched the electron ebuilds to ship the wrapper (a common file which gets customized by each ebuild). I also patched the vscode ebuild to do the same (the same approach has been used in Arch Linux).
I've tested eselect-electron, vscode and electron:19. I didn't test electron:20/21/22/23 but I don't see any reason why they shouldn't work.

I shipped a new version of each ebuild (-`r1`), so to ease the review here is the difference:

```
niko@talos2 /var/db/repos/pf4public/dev-util/electron $ diff -ruN electron-19.1.9.ebuild electron-19.1.9-r1.ebuild 
--- electron-19.1.9.ebuild	2022-11-30 21:14:44.951030858 +0100
+++ electron-19.1.9-r1.ebuild	2023-02-25 19:26:59.514362714 +0100
@@ -1923,6 +1923,10 @@
 	# bundled eu-strip is for amd64 only and we don't want to pre-stripped binaries
 	mkdir -p buildtools/third_party/eu-strip/bin || die
 	ln -s "${EPREFIX}"/bin/true buildtools/third_party/eu-strip/bin/eu-strip || die
+
+	cp "${FILESDIR}/electron-launcher.sh" "${WORKDIR}"
+	sed -i "s|@ELECTRON@|electron-${PV%%.*}|" "${WORKDIR}/electron-launcher.sh"
+	sed -i "s|@LIBDIR@|$(get_libdir)|" "${WORKDIR}/electron-launcher.sh"
 }
 
 src_configure() {
@@ -2336,10 +2340,11 @@
 	local CHROMIUM_HOME="/usr/$(get_libdir)/electron-${PV%%.*}"
 	exeinto "${CHROMIUM_HOME}"
 	doexe out/Release/electron
-	dosym "${CHROMIUM_HOME}/electron" "/usr/bin/electron-${PV%%.*}"
-
 	doexe "${FILESDIR}/node"
 
+	exeinto "/usr/bin"
+	newexe "${WORKDIR}/electron-launcher.sh" "electron-${PV%%.*}"
+
 	pushd out/Release/locales > /dev/null || die
 	chromium_remove_language_paks
 	popd
```

```
niko@talos2 /var/db/repos/pf4public/app-editors/vscode $ diff -ruN vscode-1.75.1.ebuild vscode-1.75.1-r1.ebuild
--- vscode-1.75.1.ebuild	2023-02-10 09:27:30.878101832 +0100
+++ vscode-1.75.1-r1.ebuild	2023-02-25 19:19:38.421157574 +0100
@@ -2473,12 +2473,16 @@
 
 	exeinto "${VSCODE_HOME}"
 	sed -i '/^ELECTRON/,+3d' "${WORKDIR}"/V*/bin/code-oss || die
+
+	awk -i inplace -v text="$(cat ${FILESDIR}/read_flags_file)" '!/^#/ && !p {print text; p=1} 1' "${WORKDIR}"/V*/bin/code-oss
+	sed -i "s|@ELECTRON@|electron-${ELECTRON_SLOT}|" "${WORKDIR}"/V*/bin/code-oss
+
 	echo "VSCODE_PATH=\"/usr/$(get_libdir)/vscode\"
 	ELECTRON_PATH=\"/usr/$(get_libdir)/electron-${ELECTRON_SLOT}\"
 	CLI=\"\${VSCODE_PATH}/out/cli.js\"
 	exec /usr/bin/env ELECTRON_RUN_AS_NODE=1 \
 	NPM_CONFIG_NODEDIR=\"\${ELECTRON_PATH}/node/\" \
-	\"\${ELECTRON_PATH}/electron\" \"\${CLI}\" --app=\"\${VSCODE_PATH}\" \"\$@\"" >> "${WORKDIR}"/V*/bin/code-oss
+	\"\${ELECTRON_PATH}/electron\" \"\${CLI}\" --app=\"\${VSCODE_PATH}\" \"\${flags[@]}\" \"\$@\"" >> "${WORKDIR}"/V*/bin/code-oss
 	doexe "${WORKDIR}"/VSCode-linux-${VSCODE_ARCH}/bin/code-oss
 	dosym "${VSCODE_HOME}/code-oss" /usr/bin/code-oss
```

Let me know if you have any question, this was a much needed change in my opinion.

### CODE REVIEW

**Comment by darkbasic** [comment]
I also tested electron 21 and electron 22 and pushed a commit to update the ppc64 patchset for electron 22.
Btw I get the `tree_sitter_tsx_external_scanner_create` issue even with electron-21.

**Comment by PF4Public** [comment]
>eselect-electron, which I discovered was completely broken

Thanks for fixing the bug there. I admit, I did a sloppy job there.

>I've tested eselect-electron, vscode and electron:19. I didn't test electron:20/21/22/23 but I don't see any reason why they shouldn't work.

Very nice of you and I agree, there should be no problems with others.

Have you had any chance to test under X?

Would you be able to add similar launcher for element-desktop?

>I also tested electron 21 and electron 22 and pushed a commit to update the ppc64 patchset for electron 22.

Thanks! Have you attempted building chromium 110 on ppc yet?

>Btw I get the tree_sitter_tsx_external_scanner_create issue even with electron-21.

I have a feeling that they changed something in their build system and it breaks the build since then. Last good (known to me) commit was `EGIT_OVERRIDE_COMMIT_MICROSOFT_VSCODE=220f9387c973de4cc44c545642ad2c90170bd3ef`. And I still use it:
```
Version: 1.75.0
Commit: 220f9387c973de4cc44c545642ad2c90170bd3ef
Datum: 2022-12-07T02:03:33.946Z
Electron: 21.4.1
Chromium: 106.0.5249.119
Node.js: 16.16.0
V8: 10.6.194.18-electron.0
Betriebssystem: Linux x64 5.15.88-gentoo
Sandkasten: No
```

Unfortunately it is more than 2 month old and fails with electron-22 and later :(

**Comment by darkbasic** [comment]
> Wouldn't it be more convenient to check ~/.config/electron-flags.conf first?

I'm doing what Arch Linux does nowadays. IIRC they used to so in the past, but they don't anymore. Anyway if we want to do so I would rather suggest to check for the generic version specific config first and eventually fallback to the general `electron-flags.conf` one (some flags are incompatible between electron versions and some exhibit some quirks).

> Have you had any chance to test under X?

Not yet, but I see no reason why it shouldn't work because we don't add any flag to the config so it won't run any additional parameter.

> Would you be able to add similar launcher for element-desktop?

Sure.

> Have you attempted building chromium 110 on ppc yet?

I'm currently using 110 but it's taking longer to get merged: https://github.com/gentoo/gentoo/pull/29647

> Unfortunately it is more than 2 month old and fails with electron-22 and later

It fails with electron-21 as well. I fear we will be stuck with electron-19 only.

**Comment by PF4Public** [comment]
> It fails with electron-21 as well. I fear we will be stuck with electron-19 only.

Have you overriden the commit? Just tested, still works for me:
```sh
/ # EGIT_OVERRIDE_COMMIT_MICROSOFT_VSCODE=220f9387c973de4cc44c545642ad2c90170bd3ef emerge -v1 vscode

These are the packages that would be merged, in order:

Calculating dependencies  ... done!
Dependency resolution took 6.98 s.

[ebuild   R   *] app-editors/vscode-9999::pf4public  USE="badge-providers build-online electron-21 substitute-urls -electron-20 -electron-22 -electron-23% -insiders -liveshare -openvsx" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB

>>> Verifying ebuild manifests
>>> Emerging (1 of 1) app-editors/vscode-9999::pf4public
>>> Installing (1 of 1) app-editors/vscode-9999::pf4public
>>> Jobs: 1 of 1 complete                           Load avg: 1.61, 1.88, 1.38

 * Messages for package app-editors/vscode-9999:

 * Using EGIT_OVERRIDE_COMMIT_MICROSOFT_VSCODE=220f9387c973de4cc44c545642ad2c90170bd3ef
 * No support will be provided.
```



> I'm doing what Arch Linux does nowadays. IIRC they used to so in the past, but they don't anymore. Anyway if we want to do so I would rather suggest to check for the version specific config first and eventually fallback to the general `electron-flags.conf` one (some flags are incompatible between electron versions and some exhibit some quirks).

However you see fits.

> I'm currently using 110 but it's taking longer to get merged: [gentoo/gentoo#29647](https://github.com/gentoo/gentoo/pull/29647)

This means I can merge your changes here (after this PR is merged of-course to avoid merge-conflicts).

**Comment by darkbasic** [comment]
> Have you overriden the commit? Just tested, still works for me

No sorry I meant with latest git master.

> However you see fits.

I think falling back to a generic electron-flags.conf if the version specific config does not exist might be a good idea, but I'd rather merge this ASAP and make the change later because testing electron ebuilds takes a lot of time and the bot keeps pushing changes in the meantime :)

By the way I've rebased this and added an -r1 ebuild for vscode 1.76. I've also noticed that it fails to build with the following:

```
[4/4] Building fresh packages...
error /var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright
Output:
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright.azureedge.net/builds/chromium/1045/chromium-linux.zip
Error: getaddrinfo EAI_AGAIN playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright.azureedge.net'
}
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright-akamai.azureedge.net/builds/chromium/1045/chromium-linux.zip
Error: getaddrinfo EAI_AGAIN playwright-akamai.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright-akamai.azureedge.net'
}
Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright-verizon.azureedge.net/builds/chromium/1045/chromium-linux.zip
Error: getaddrinfo EAI_AGAIN playwright-verizon.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright-verizon.azureedge.net'
}
/var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/index.js:644
      throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
            ^

Error: Failed to download Chromium 110.0.5481.38 (playwright build v1045), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/browserFetcher.js:95:16)
    at ChildProcess.emit (node:events:526:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at /var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/index.js:644:13
    at async Registry._downloadExecutable (/var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/index.js:643:5)
    at async Registry.install (/var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/index.js:607:9)
    at async installBrowsersForNpmInstall (/var/tmp/portage/app-editors/vscode-1.76.0-r1/work/vscode-1.76.0/node_modules/playwright/node_modules/playwright-core/lib/server/registry/index.js:782:3)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

It's the offline build of course.

> This means I can merge your changes here

Sure.

**Comment by darkbasic** [comment]
> So is everything ready for merge then? Other things (element-desktop) will be left for later in this case, correct?

Yes.

Btw it looks like tree-sitter is not a dependency of web-tree-sitter:

```
niko@talos2 ~/devel/zg $ yarn init -y
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.04s.

niko@talos2 ~/devel/zg $ yarn add @vscode/l10n-dev@0.0.21
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 33 new dependencies.
info Direct dependencies
└─ @vscode/l10n-dev@0.0.21
info All dependencies
├─ @vscode/l10n-dev@0.0.21
├─ ansi-regex@5.0.1
├─ ansi-styles@4.3.0
├─ balanced-match@1.0.2
├─ brace-expansion@2.0.1
├─ cliui@8.0.1
├─ color-convert@2.0.1
├─ color-name@1.1.4
├─ deepmerge-json@1.5.0
├─ emoji-regex@8.0.0
├─ escalade@3.1.1
├─ flat@5.0.2
├─ fs.realpath@1.0.0
├─ get-caller-file@2.0.5
├─ get-stdin@7.0.0
├─ glob@8.1.0
├─ inflight@1.0.6
├─ inherits@2.0.4
├─ is-fullwidth-code-point@3.0.0
├─ minimatch@5.1.6
├─ pseudo-localization@2.4.0
├─ require-directory@2.1.1
├─ sax@1.2.4
├─ string-width@4.2.3
├─ strip-ansi@6.0.1
├─ typescript@4.9.5
├─ web-tree-sitter@0.20.7
├─ wrap-ansi@7.0.0
├─ xml2js@0.4.23
├─ xmlbuilder@11.0.1
├─ y18n@5.0.8
├─ yargs-parser@21.1.1
└─ yargs@17.7.1
Done in 2.47s.

niko@talos2 ~/devel/zg $ yarn why web-tree-sitter
yarn why v1.22.19
[1/4] Why do we have the module "web-tree-sitter"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "web-tree-sitter@0.20.7"
info Reasons this module exists
   - "@vscode#l10n-dev" depends on it
   - Hoisted from "@vscode#l10n-dev#web-tree-sitter"
info Disk size without dependencies: "256KB"
info Disk size with unique dependencies: "256KB"
info Disk size with transitive dependencies: "256KB"
info Number of shared dependencies: 0
Done in 0.14s.

niko@talos2 ~/devel/zg $ yarn why tree-sitter
yarn why v1.22.19
[1/4] Why do we have the module "tree-sitter"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 0.14s.
```

**Comment by PF4Public** [comment]
Merged, thanks!

>Btw it looks like tree-sitter is not a dependency of web-tree-sitter:

It could be an indirect dependency. When I removed all mentions of tree-sitter from `product.json` it was still searching for it and failed. Besides it is stated so in a commit I linked: https://github.com/microsoft/vscode/commit/0510da84dd109e682a654465ff1bdc376b76e231



> By the way I've rebased this and added an -r1 ebuild for vscode 1.76. I've also noticed that it fails to build with the following:

I hope `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` could get rid of it.

**Comment by darkbasic** [comment]
@PF4Public `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true` did the trick for me

**Pull request merged**
