### PR TITLE
dev-util/electron: fix 29 on ppc64le

### PR DESCRIPTION
**Pull request by darkbasic**
Has been tested on Chromium 122 but should work on electron as well.
Does vscode-999 work with electron 29? If so could you please add the corresponding use flag to the ebuild?
v8 sandbox has been merged upstream on December 19 so I would like to test it with a modern version of electron.

### CODE REVIEW

**Comment by PF4Public** [comment]
> Does vscode-999 work with electron 29?

No idea, but I expect if to fail due to the fact that it has node-20, the system node is also at 20, so we have no way of overcoming the long lasting issue in vscode. Of-course I was about to add 29 to all ebuilds, just didn't have time yet.

**Comment by darkbasic** [comment]
How the hell didn't they release an updated tree-sitter version yet? I honestly can't believe it...

**Comment by darkbasic** [comment]
By the way they claim that vscode 1.82+ should have fixed the issue: https://github.com/cucumber/vscode/issues/164#issuecomment-1727870733

**Comment by PF4Public** [comment]
> By the way they claim that vscode 1.82+ should have fixed the issue: [cucumber/vscode#164 (comment)](https://github.com/cucumber/vscode/issues/164#issuecomment-1727870733)

They claim that their plugin is fixed. treesitter-related issues seem to be untouched since the reporting. See the [recent workflow run](https://github.com/PF4Public/gentoo-overlay/actions/runs/8088450947/job/22103585022) for example:
```sh
>>> Compiling source in /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0 ...
[03:15:12] Using gulpfile /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/gulpfile.js
[03:15:12] Starting 'vscode-linux-x64-min'...
[03:15:12] Starting clean-out-build ...
[03:15:12] Finished clean-out-build after 2 ms
[03:15:12] Starting build-web-node-paths ...
[03:15:12] Finished build-web-node-paths after 2 ms
[03:15:12] Starting compile-api-proposal-names ...
[03:15:12] Starting compilation api-proposal-names...
Unhandled Rejection at: Promise Promise {
  <rejected> Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
      at reportUndefinedSymbols (/var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
      at postInstantiation (/var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
      at /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:17752
      at async /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/@vscode/l10n-dev/dist/main.js:329:10
      at async /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/@vscode/l10n-dev/dist/main.js:318:22
} reason: Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
    at reportUndefinedSymbols (/var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
    at postInstantiation (/var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
    at /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/web-tree-sitter/tree-sitter.js:1:17752
    at async /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/@vscode/l10n-dev/dist/main.js:329:10
    at async /var/tmp/portage/app-editors/vscode-1.87.0/work/vscode-1.87.0/node_modules/@vscode/l10n-dev/dist/main.js:318:22
[03:15:12] The following tasks did not complete: vscode-linux-x64-min
[03:15:12] Did you forget to signal async completion?
 * ERROR: app-editors/vscode-1.87.0::pf4public failed (compile phase):
```

**Comment by darkbasic** [comment]
> their plugin

Yes but since they had our very same tree-sitter issue I hoped that some fix had landed in tree-sitter in the meantime. Apparently there are multiple issues at play here in tree-sitter.

**Comment by darkbasic** [comment]
By the way did you try to bump all tree-sitter instances to latest 0.20.6 via yarn resolutions? I doubt it helps but it might be worth trying.

**Comment by PF4Public** [comment]
> By the way did you try to bump all tree-sitter instances to latest 0.20.6 via yarn resolutions?

No, but it is doable, see:
https://github.com/PF4Public/gentoo-overlay/blob/5fcdf34285df0b2df2dab50e985b56809a4b8b21/app-editors/vscode/vscode-9999.ebuild#L252-L258

**Comment by darkbasic** [comment]
Unfortunately I'm stuck at the step prior: compiling electron.
I get this error:
```
[131/139] python3.11 ../../electron/script/generate-config-gypi.py /var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/out/Release/gen/config.gypi ppc64
FAILED: gen/config.gypi 
python3.11 ../../electron/script/generate-config-gypi.py /var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/out/Release/gen/config.gypi ppc64
Package http_parser was not found in the pkg-config search path.
Perhaps you should add the directory containing `http_parser.pc'
to the PKG_CONFIG_PATH environment variable
Package 'http_parser', required by 'virtual:world', not found
gyp: --without-dtrace not found (cwd: /var/tmp/portage/dev-util/electron-29.1.0/work/node-v20.9.0) while trying to load --without-dtrace
Error running GYP
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/out/Release/../../electron/script/generate-config-gypi.py", line 68, in <module>
    sys.exit(main(sys.argv[1], sys.argv[2]))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/out/Release/../../electron/script/generate-config-gypi.py", line 49, in main
    run_node_configure(target_cpu)
  File "/var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/out/Release/../../electron/script/generate-config-gypi.py", line 27, in run_node_configure
    subprocess.check_call([sys.executable, configure] + args)
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.11', '/var/tmp/portage/dev-util/electron-29.1.0/work/chromium-122.0.6261.70/third_party/electron_node/configure.py', '--dest-cpu', 'ppc64', '--experimental-enable-pointer-compression', '--without-bundled-v8', '--shared-openssl', '--shared-zlib', '--without-dtrace', '--without-npm', '--shared-cares', '--shared-http-parser', '--shared-nghttp2', '--with-intl=system-icu']' returned non-zero exit status 1.
ninja: build stopped: subcommand failed.
```

**Comment by PF4Public** [comment]
>Package http_parser was not found in the pkg-config search path.

Try merging it

**Comment by darkbasic** [comment]
If you mean `net-libs/http-parser` I've already tried emerging it and didn't help. Full build log with `net-libs/http-parser` installed:
[electron-29.1.0.build.log](https://github.com/PF4Public/gentoo-overlay/files/14481319/electron-29.1.0.build.log)

**Comment by PF4Public** [comment]
I'd better merge your PR before they do any new tags.



> If you mean `net-libs/http-parser` I've already tried emerging it and didn't help. Full build log with `net-libs/http-parser` installed:
> [electron-29.1.0.build.log](https://github.com/PF4Public/gentoo-overlay/files/14481319/electron-29.1.0.build.log)

I'll get to it later when I attemp building electron-29 myself.

**Comment by PF4Public** [comment]
@darkbasic Sorry, it has nothing to do with `http-parser`, they just removed `dtrace` option in node-19, therefore it failed. Fixed in 89d095514bbd38d1b22c20d8cdd9f6726b532534

**Comment by darkbasic** [comment]
image

electron 29 works, next step is vscode. Let me know if it works with electron 29 on x64, otherwise I will try to use fnm to retrieve whatever node.js version upstream advices you to use.

**Comment by PF4Public** [comment]
> next step is vscode

As I suspected, it does not build. With system node:

```sh
[21:27:55] Starting compilation...
Unhandled Rejection at: Promise Promise {
  <rejected> Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
      at reportUndefinedSymbols (/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
      at postInstantiation (/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
      at /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:17752
      at async /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/@vscode/l10n-dev/dist/main.js:329:10
      at async /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/@vscode/l10n-dev/dist/main.js:318:22
} reason: Error: bad export type for `tree_sitter_tsx_external_scanner_create`: undefined
    at reportUndefinedSymbols (/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:19748)
    at postInstantiation (/var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:17027)
    at /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/web-tree-sitter/tree-sitter.js:1:17752
    at async /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/@vscode/l10n-dev/dist/main.js:329:10
    at async /var/tmp/portage/app-editors/vscode-9999/work/vscode-9999/node_modules/@vscode/l10n-dev/dist/main.js:318:22
[21:27:56] The following tasks did not complete: vscode-linux-x64-min
[21:27:56] Did you forget to signal async completion?
```

With built-in node it randomly fails later during the build. Over 5 attempts, none succeeded.

**Comment by darkbasic** [comment]
Weird, it *did* compile successfully for me:

image

The problem is that it still segfaults:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/usr/lib64/electron-29/electron --app=/usr/lib64/vscode '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00003fff9daa7c48 in ?? () from /usr/lib64/libc.so.6
[Current thread is 1 (Thread 0x3fffa1d8d040 (LWP 1144286))]
(gdb) bt full
#0  0x00003fff9daa7c48 in ??? () at /usr/lib64/libc.so.6
#1  0x00003fff9daa7bd4 in pthread_join () at /usr/lib64/libc.so.6
#2  0x000000011adc13d8 in uv_thread_join (tid=<optimized out>) at ../../third_party/electron_node/deps/uv/src/unix/thread.c:286
#3  0x000000011b065a88 in electron::NodeBindings::~NodeBindings (this=0x2e3800700800) at ../../electron/shell/common/node_bindings.cc:428
#4  0x000000011b0c8b38 in electron::NodeBindingsLinux::~NodeBindingsLinux (this=0x2e3800700800) at ../../electron/shell/common/node_bindings_linux.h:13
#5  0x000000011af55cac in std::default_delete<electron::NodeBindings>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:99
#6  std::unique_ptr<electron::NodeBindings, std::default_delete<electron::NodeBindings> >::~unique_ptr (this=0x2e3800140c78) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:404
        __ptr = @0x2e3800140c78: 0x2e3800700800
#7  electron::ElectronBrowserMainParts::~ElectronBrowserMainParts (this=0x2e3800140c30) at ../../electron/shell/browser/electron_browser_main_parts.cc:189
#8  0x000000011af55e58 in electron::ElectronBrowserMainParts::~ElectronBrowserMainParts (this=0x2e3800140c30) at ../../electron/shell/browser/electron_browser_main_parts.cc:189
#9  0x000000011ea94004 in std::default_delete<content::BrowserMainParts>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:99
#10 std::unique_ptr<content::BrowserMainParts, std::default_delete<content::BrowserMainParts> >::~unique_ptr (this=0x2e38006c0a40) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:404
        __ptr = @0x2e38006c0a40: 0x2e3800140c30
#11 content::BrowserMainLoop::~BrowserMainLoop (this=0x2e38006c09a0) at ../../content/browser/browser_main_loop.cc:518
#12 0x000000011ea94228 in content::BrowserMainLoop::~BrowserMainLoop (this=0x2e38006c09a0) at ../../content/browser/browser_main_loop.cc:514
#13 0x000000011ea99d20 in std::default_delete<content::BrowserMainLoop>::operator() (this=<optimized out>, __ptr=<optimized out>) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:99
#14 std::__uniq_ptr_impl<content::BrowserMainLoop, std::default_delete<content::BrowserMainLoop> >::reset (this=0x2e38000c0380, __p=0x0) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:211
        __old_p = <optimized out>
#15 std::unique_ptr<content::BrowserMainLoop, std::default_delete<content::BrowserMainLoop> >::reset (this=0x2e38000c0380, __p=0x0) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:509
#16 content::BrowserMainRunnerImpl::Shutdown (this=0x2e38000c0360) at ../../content/browser/browser_main_runner_impl.cc:182
        trace_event_unique_tracer173 = {category_group_enabled_ = 0x0, name_ = 0xaaaaaaaaaaaaaaaa <error: Cannot access memory at address 0xaaaaaaaaaaaaaaaa>, event_handle_ = {chunk_seq = 2863311530, chunk_index = 44739242, event_index = 42}}
        trace_event_unique_k_category_group_enabled173 = <optimized out>
        trace_event_unique_category_group_enabled173 = <optimized out>
#17 0x000000011ea99688 in content::BrowserMainRunnerImpl::~BrowserMainRunnerImpl (this=0x2e38000c0360) at ../../content/browser/browser_main_runner_impl.cc:67
#18 content::BrowserMainRunnerImpl::~BrowserMainRunnerImpl (this=0x2e38000c0360) at ../../content/browser/browser_main_runner_impl.cc:65
#19 0x000000011ea93a7c in std::default_delete<content::BrowserMainRunnerImpl>::operator() (this=0x3fffebfda378, __ptr=<optimized out>) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:99
#20 std::unique_ptr<content::BrowserMainRunnerImpl, std::default_delete<content::BrowserMainRunnerImpl> >::~unique_ptr (this=0x3fffebfda378) at /usr/lib/gcc/powerpc64le-unknown-linux-gnu/13/include/g++-v13/bits/unique_ptr.h:404
        __ptr = @0x3fffebfda378: 0x2e38000c0360
#21 content::BrowserMain (parameters=...) at ../../content/browser/browser_main.cc:46
        shutdown_time = -6148914694099828736
        main_runner = std::unique_ptr<content::BrowserMainRunnerImpl> = {get() = 0x2e38000c0360}
        exit_code = 787296
#22 0x000000011b46eb30 in content::RunBrowserProcessMain (main_function_params=..., delegate=0x3fffebfdaab0) at ../../content/app/content_main_runner_impl.cc:712
        exit_code = {<absl::variant_internal::VariantMoveAssignBaseNontrivial> = {<absl::variant_internal::VariantMoveBaseNontrivial> = {<absl::variant_internal::VariantStateBaseDestructorNontrivial> = {<absl::variant_internal::VariantStateBase<int>> = {state_ = {head = 0, tail = {head = {command_line = {static Traits = partition_alloc::internal::RawPtrTraits::kMayDangle, static kZeroOnConstruct = <optimized out>, static kZeroOnMove = true, static kZeroOnDestruct = true, wrapped_ptr_ = 0x0, tracer_ = {<No data fields>}}, zygote_child = false, needs_startup_tracing_after_mojo_init = false, hang_watcher_not_started_time = std::optional [no contained value], ui_task = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, created_main_parts_closure = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, startup_data = std::unique_ptr<content::StartupData> = {get() = 0x0}}, tail = {<No data fields>}}}, index_ = 1}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}
#23 0x000000011b4706bc in content::ContentMainRunnerImpl::RunBrowser (this=0x219c00740e00, main_params=..., start_minimal_browser=<optimized out>) at ../../content/app/content_main_runner_impl.cc:1299
#24 0x000000011b470458 in content::ContentMainRunnerImpl::Run (this=0x219c00740e00) at ../../content/app/content_main_runner_impl.cc:1144
        main_params = {command_line = {static Traits = partition_alloc::internal::RawPtrTraits::kMayDangle, static kZeroOnConstruct = <optimized out>, static kZeroOnMove = true, static kZeroOnDestruct = true, wrapped_ptr_ = 0x0, tracer_ = {<No data fields>}}, zygote_child = false, needs_startup_tracing_after_mojo_init = false, hang_watcher_not_started_time = std::optional [no contained value], ui_task = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, created_main_parts_closure = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, startup_data = std::unique_ptr<content::StartupData> = {get() = 0x0}}
        command_line = <optimized out>
        process_type = ""
        start_minimal_browser = <optimized out>
#25 0x000000011b46d1e8 in content::RunContentProcess (params=..., content_main_runner=0x219c00740e00) at ../../content/app/content_main.cc:334
        is_initialized = true
        exit_code = <optimized out>
#26 0x000000011b46d770 in content::ContentMain (params=...) at ../../content/app/content_main.cc:347
        runner = std::unique_ptr<content::ContentMainRunner> = {get() = 0x219c00740e00}
#27 0x000000011adcbc18 in main (argc=<optimized out>, argv=0x3fffebfdaf68) at ../../electron/shell/app/electron_main_linux.cc:45
        delegate = {<content::ContentMainDelegate> = {_vptr$ContentMainDelegate = 0x128181760 <vtable for electron::ElectronMainDelegate+16>}, static kNonWildcardDomainNonPortSchemes = {0x1277866e0 <extensions::kExtensionScheme> "chrome-extension"}, static kNonWildcardDomainNonPortSchemesSize = 282584257676671, browser_client_ = std::unique_ptr<content::ContentBrowserClient> = {get() = 0x219c002c0b00}, content_client_ = std::unique_ptr<content::ContentClient> = {get() = 0x219c00284d10}, gpu_client_ = std::unique_ptr<content::ContentGpuClient> = {get() = 0x0}, renderer_client_ = std::unique_ptr<content::ContentRendererClient> = {get() = 0x0}, utility_client_ = std::unique_ptr<content::ContentUtilityClient> = {get() = 0x0}, tracing_sampler_profiler_ = std::unique_ptr<tracing::TracingSamplerProfiler> = {get() = 0x219c0068c600}}
        params = {delegate = {static Traits = partition_alloc::internal::RawPtrTraits::kEmpty, static kZeroOnConstruct = <optimized out>, static kZeroOnMove = true, static kZeroOnDestruct = true, wrapped_ptr_ = 0x0, tracer_ = {<No data fields>}}, argc = 2, argv = {static Traits = partition_alloc::internal::RawPtrTraits::kEmpty, static kZeroOnConstruct = <optimized out>, static kZeroOnMove = true, static kZeroOnDestruct = true, wrapped_ptr_ = 0x0, tracer_ = {<No data fields>}}, ui_task = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, created_main_parts_closure = {holder_ = {bind_state_ = {ptr_ = 0x0}}}, minimal_browser_mode = false}
```

I wonder if v8 sandbox somehow didn't find its way into electron 22 or if it's a completely different issue...
Maybe it's worth trying to build it with node 18 first, should I use `+temp-fix` with it or not?

**Comment by PF4Public** [comment]
Update: although I couldn't build it in KVM-guest-chroot from like 10 attempts, it did work on a real hardware from the 3-rd try:
image

>The problem is that it still segfaults

Hmm, don't know what that might be :(

**Comment by PF4Public** [comment]
And the stable made it on the first attempt, so overall it is useable on amd64:
image

**Comment by darkbasic** [comment]
@PF4Public why despite `-temp-fix` you still use a mix of electron node and system node?

I was under the impression that `-temp-fix` would also do the following:

```
diff --git a/app-editors/vscode/vscode-9999.ebuild b/app-editors/vscode/vscode-9999.ebuild
index 8db46bbd..9915093e 100644
--- a/app-editors/vscode/vscode-9999.ebuild
+++ b/app-editors/vscode/vscode-9999.ebuild
@@ -272,18 +272,18 @@ src_configure() {
 
 	ebegin "Installing node_modules"
 	# yarn config set yarn-offline-mirror ${T}/yarn_cache || die
-	OLD_PATH=$PATH
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
-	export PATH
-	export CFLAGS="${CFLAGS} -I/usr/include/electron-${ELECTRON_SLOT}/node"
-	export CPPFLAGS="${CPPFLAGS} -I/usr/include/electron-${ELECTRON_SLOT}/node"
+	#OLD_PATH=$PATH
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
+	#export PATH
+	#export CFLAGS="${CFLAGS} -I/usr/include/electron-${ELECTRON_SLOT}/node"
+	#export CPPFLAGS="${CPPFLAGS} -I/usr/include/electron-${ELECTRON_SLOT}/node"
 	export ELECTRON_SKIP_BINARY_DOWNLOAD=1
 	export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
 	# echo "$PATH"
 	yarn config set disable-self-update-check true || die
-	yarn config set nodedir /usr/include/electron-${ELECTRON_SLOT}/node || die
+	#yarn config set nodedir /usr/include/electron-${ELECTRON_SLOT}/node || die
 	if ! use build-online; then
 		ONLINE_OFFLINE="--offline"
 		yarn config set yarn-offline-mirror "${DISTDIR}" || die
@@ -302,7 +302,7 @@ src_configure() {
 	# For webpack >= 5.61.0
 	sed -i 's/case "sha512"/case "md4"/' node_modules/webpack/lib/util/createHash.js || die
 
-	export PATH=${OLD_PATH}
+	#export PATH=${OLD_PATH}
 
 	einfo "Restoring vscode-ripgrep"
 	pushd "node_modules/@vscode" > /dev/null || die
@@ -341,11 +341,11 @@ src_compile() {
 	fi
 	export BUILD_SOURCEVERSION="${COMMIT_ID}"
 
-	OLD_PATH=$PATH
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
-	export PATH
+	#OLD_PATH=$PATH
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
+	#export PATH
 	export NODE_OPTIONS="--max-old-space-size=12192 --heapsnapshot-near-heap-limit=5"
 
 	if use temp-fix; then
@@ -373,15 +373,15 @@ src_compile() {
 		fi
 	fi
 
-	export PATH=${OLD_PATH}
+	#export PATH=${OLD_PATH}
 }
 
 src_install() {
-	OLD_PATH=$PATH
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
-	PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
-	export PATH
+	#OLD_PATH=$PATH
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin/node-gyp-bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}/node_modules/npm/bin:$PATH"
+	#PATH="/usr/$(get_libdir)/electron-${ELECTRON_SLOT}:$PATH"
+	#export PATH
 
 	if use temp-fix; then
 	YARN_CACHE_FOLDER="${T}/.yarn-cache" node node_modules/gulp/bin/gulp.js vscode-linux-${VSCODE_ARCH}-prepare-deb || die
@@ -435,7 +435,7 @@ src_install() {
 	doins appdata/*
 
 	popd > /dev/null || die
-	export PATH=${OLD_PATH}
+	#export PATH=${OLD_PATH}
 }
 
 
```

Instead electron node is still used everywhere in the ebuild except from a few selected places:

```
niko@talos2 /var/db/repos/pf4public/app-editors/vscode $ grep -r "/usr/bin/node" vscode-9999.ebuild 
	# Real nodejs needed (/usr/bin/node). See https://github.com/microsoft/vscode-l10n/issues/104
	/usr/bin/node node_modules/gulp/bin/gulp.js vscode-linux-${VSCODE_ARCH}-min || die
		# Real nodejs needed (/usr/bin/node). See https://github.com/microsoft/vscode-l10n/issues/104
		/usr/bin/node node_modules/gulp/bin/gulp.js vscode-reh-linux-${VSCODE_ARCH}-min || die
		# Real nodejs needed (/usr/bin/node). See https://github.com/microsoft/vscode-l10n/issues/104
		/usr/bin/node node_modules/gulp/bin/gulp.js vscode-reh-web-linux-${VSCODE_ARCH}-min || die
	# Real nodejs needed (/usr/bin/node). See https://github.com/microsoft/vscode-l10n/issues/104
	YARN_CACHE_FOLDER="${T}/.yarn-cache" /usr/bin/node node_modules/gulp/bin/gulp.js vscode-linux-${VSCODE_ARCH}-prepare-deb || die
```

**Comment by PF4Public** [comment]
> why despite `-temp-fix` you still use a mix of electron node and system node?

Because you don't want vscode native modules be built against system node.

> Instead electron node is still being used everywhere in the ebuild except from a few selected places:

You're taking it out of context. See it in context:
https://github.com/PF4Public/gentoo-overlay/blob/46a0f35f1f3522a7e24144cb93678e733d196d23/app-editors/vscode/vscode-9999.ebuild#L351-L356

**Comment by darkbasic** [comment]
The point is that yarn install complains about using an unsupported node version (electron's one). Does upstream expect you to run `yarn install` via electron's node?

**Comment by PF4Public** [comment]
> Does upstream expect you to run `yarn install` via electron's node?

Probably no

**Comment by darkbasic** [comment]
That's what I meant with -temp-fix not doing what upstream expects.
Using system's node is not super useful in Gentoo because you can't have multiple slots, but you can download official node 18 binaries and use them to build vscode via portage and it compiles succesfully. Still segfaults though.

**Comment by darkbasic** [comment]
I did the first build with the ebuild untouched and +temp-fix but it still segfaulted. I've also tried to use yarn from fnm but it segfaults as well.

**Comment by PF4Public** [comment]
It is smething specific to ppc then.

**Comment by darkbasic** [comment]
https://github.com/tree-sitter/tree-sitter/issues/2338#issuecomment-2040043357

**Comment by PF4Public** [comment]
> [tree-sitter/tree-sitter#2338 (comment)](https://github.com/tree-sitter/tree-sitter/issues/2338#issuecomment-2040043357)

I've updated ebuild to pull changes from `electron-29.x.y` branch. It [fails in the workflow](https://github.com/PF4Public/gentoo-overlay/actions/runs/8583276878/job/23522686814) for some reason though.

**Comment by darkbasic** [comment]
Uhm... maybe it's time to bump the issue on the vscode repo?

**Comment by PF4Public** [comment]
To be honest, I haven't had time yet to dig deeper.

**Comment by PF4Public** [comment]
@darkbasic They updated the needed components and now 9999 builds with system node (`-temp-fix`) from the first attempt. Giveit a try.

**Pull request merged**
