### PR TITLE
app-editors/vscode: add arm64 support

### PR DESCRIPTION
**Pull request by ZerdoX-x**

### CODE REVIEW

**Comment by PF4Public** [comment]
Please add "arm" → "armhf" and place both arms between "x86" and "ppc64".

**Comment by ZerdoX-x** [comment]
I'll try to push this later, sorry :D I hope I'll finish it this week

**Comment by ZerdoX-x** [comment]
@PF4Public hi :) I finally got some time to finish this PR. could you please check it?

Commit history is a bit dirty, but I guess you are able to squash commits, at least this is possible in gitlab interface, not sure about github. Or I can force push changes to make them one nice and clear commit. Please review and give feedback if needed

**Comment by ZerdoX-x** [comment]
Failed because of heap memory limits :)

**Comment by PF4Public** [comment]
> Commit history is a bit dirty, but I guess you are able to squash commits […] Or I can force push changes to make them one nice and clear commit. 

No worries, I can make it myself.

>Please review and give feedback if needed

All good, thanks.



> Failed because of heap memory limits :)

Yep, its getting worse :( https://github.com/PF4Public/gentoo-overlay/actions/workflows/vscode.yml

**Pull request merged**
