### PR TITLE
feat(electron:17): ppc64le support

### PR DESCRIPTION
**Pull request by darkbasic**
Segfaults, do not merge yet.

```
$ electron-17

Electron 17.0.1 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
[471643:0227/000628.467204:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[471643:0227/000628.472150:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[471603:0227/000628.490654:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
Segmentation fault (core dumped)
```

Core dump: https://drive.google.com/file/d/1l9qio2FeNLtBLyyDvhFfT_goITov70n9/view?usp=sharing

### CODE REVIEW

**Comment by PF4Public** [comment]
Are you trying to make it work under Wayland or it crashes even under X11?

**Comment by PF4Public** [comment]
Just FYI: I've updated electron to 17.1.0. It has the newer chromium. Perhaps could be easier for you to work with.

Also Microsoft wreaks chaos upon us. They've reverted vscode back to 13. They have however a new branch for 17. I'll deal with it soon.

**Comment by darkbasic** [comment]
> Are you trying to make it work under Wayland or it crashes even under X11?

I've compiled it with wayland support, but I had both `CHROMIUM_FLAGS="--ozone-platform=x11"` in `/etc/chromium/default` and `--ozone-platform=x11` in `~/.config/electron-flags.conf`. Apparently they have no effects whatsoever because running `electron-17 --ozone-platform=x11` works instead. This is weird because I run Chromium 98 with `--ozone-platform=wayland` and it works without issues.

> I've updated electron to 17.1.0

I'll try it but I don't have much hope because Chromium 98.0.4758.80 used to work on Wayland as well before I upgrade to 102.

> Also Microsoft wreaks chaos upon us. They've reverted vscode back to electron-13.

Again? :(

> They have however a new branch for 17

That's good news: 16 had several issues with Wayland which they had some difficulties to backport. Going straight to 17 might be a good idea.

**Comment by PF4Public** [comment]
> I've compiled it with wayland support, but I had both `CHROMIUM_FLAGS="--ozone-platform=x11"` in `/etc/chromium/default` and `--ozone-platform=x11` in `~/.config/electron-flags.conf`. Apparently they have no effects whatsoever because running `electron-17 --ozone-platform=x11` works instead. This is weird because I run Chromium 98 with `--ozone-platform=wayland` and it works without issues.

I'm afraid I cannot help you with wayland as I don't use it.

> Chromium 98.0.4758.80 used to work on Wayland as well before I upgrade to 102.

Do I keep electron 17.0.1 along with 17.1.0 then?

> Again? :(

They seem to have enormous amounts of manpower to effortlessly shake things. I tried once ~playing this game~ reverting the "reverting" thing, but very soon gave up. There exists an artifact of those days in case I want to play again :)
https://github.com/PF4Public/gentoo-overlay/blob/ad53e258e2ee8861a6940b1230ed701da248e86b/app-editors/vscode/vscode-9999.ebuild#L96-L97

> > They have however a new branch for 17
> 
> … Going straight to 17 might be a good idea.

Combined with `electron-17.x.y` branch of vscode it produces a working solution:
image

**Comment by darkbasic** [comment]
> Do I keep electron 17.0.1 along with 17.1.0 then?

As you prefer: both work on x11 and both don't work on wayland. I've updated this PR to patch both, so you can decide which ones you want to keep. I wanted to mask the `wayland` use on electron for the ppc64 arch, but I guess you can't tamper with profiles on overlays so I think this PR should be ready as is.

**Comment by PF4Public** [comment]
> I guess you can't tamper with profiles on overlays

AFAIK you can. But I do not bother doing so in my overlay.

> I wanted to mask the `wayland` use on electron for the ppc64 arch

We may put a warning about that and prematurely fail the build like this:

https://github.com/PF4Public/gentoo-overlay/blob/5c634b639992d63110ba33af03e6c3a57619afec/www-client/ungoogled-chromium/ungoogled-chromium-99.0.4844.45-r1.ebuild#L267-L274

> you can decide which ones you want to keep

I'd like to keep the latest one if you don't mind.

**Comment by darkbasic** [comment]
> AFAIK you can. But I do not bother doing so in my overlay.

Uhm... that's weird because I've tried it and it didn't work, thus I deducted it wouldn't work in overlays.

> We may put a warning about that and prematurely fail the build like this

Better than nothing I'd guess.

> I'd like to keep the latest one if you don't mind.

Fine for me.

**Comment by darkbasic** [comment]
Don't merge this yet, it might be an issue on all archs and there might be a fix available.

**Comment by darkbasic** [comment]
I confirm 16.0.8-2 didn't work either on Arch Linux x86_64, thus the fix for Wayland must be somewhere in this diff: https://github.com/archlinux/svntogit-community/commit/b3dcaee8cfcdf7a3e2f32169ea6a5586940cdacd

**Comment by darkbasic** [comment]
I didn't manage to figure out what fixed it on the newest Arch Linux PKGBUILD, so I'm just warning about potential wayland issues (on any arch) for the moment. You can merge it.

**Comment by PF4Public** [comment]
Thanks! Merged!

**Pull request merged**
