### PR TITLE
[WIP] fix(ungoogled-chromium-99.0.4844.45-r1): ppc64

### PR DESCRIPTION
**Pull request by darkbasic**
Tentative forward port. Do not merge.

```
[5733/24260] clang++ -MMD -MF obj/base/base/nonscannable_memory.o.d -DUSE_SYMBOLIZE -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wshadow -fno-omit-frame-pointer -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -Wexit-time-destructors -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++17 -Wno-trigraphs -fno-aligned-new -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -O2 -pipe -mcpu=power9 -mtune=power9 -fPIC -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wno-unknown-warning-option -c ../../base/memory/nonscannable_memory.cc -o obj/base/base/nonscannable_memory.o
[31mFAILED: [0mobj/base/base/nonscannable_memory.o 
clang++ -MMD -MF obj/base/base/nonscannable_memory.o.d -DUSE_SYMBOLIZE -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_OZONE=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBASE_IMPLEMENTATION -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DUSING_SYSTEM_ICU=1 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_STATIC -DU_IMPORT=U_EXPORT -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-delete-null-pointer-checks -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -no-canonical-prefixes -Wimplicit-fallthrough -Wunreachable-code-aggressive -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wloop-analysis -Wno-unneeded-internal-declaration -Wenum-compare-conditional -Wno-psabi -Wno-ignored-pragma-optimize -Wshadow -fno-omit-frame-pointer -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -Wexit-time-destructors -DPROTOBUF_ALLOW_DEPRECATED=1 -std=c++17 -Wno-trigraphs -fno-aligned-new -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -O2 -pipe -mcpu=power9 -mtune=power9 -fPIC -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wno-unknown-warning-option -c ../../base/memory/nonscannable_memory.cc -o obj/base/base/nonscannable_memory.o
In file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
In file included from ../../base/allocator/partition_allocator/partition_root.h:52:
In file included from ../../base/allocator/partition_allocator/partition_direct_map_extent.h:10:
[1m../../base/allocator/partition_allocator/partition_page.h:146:3: [0m[0;1;31merror: [0m[1mstatic_assert failed due to requirement 'kMaxSlotsPerSlotSpan < (1 << kMaxSlotsPerSlotSpanBits)' ""[0m
  static_assert(kMaxSlotsPerSlotSpan < (1 << kMaxSlotsPerSlotSpanBits), "");
[0;1;32m  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m../../base/allocator/partition_allocator/partition_page.h:366:15: [0m[0;1;31merror: [0m[1mstatic_assert expression is not an integral constant expression[0m
static_assert(offsetof(PartitionPage<ThreadSafe>, slot_span_metadata) == 0, "");
[0;1;32m              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m/usr/lib/llvm/13/bin/../../../../lib/clang/13.0.0/include/stddef.h:104:24: [0m[0;1;30mnote: [0mexpanded from macro 'offsetof'[0m
#define offsetof(t, d) __builtin_offsetof(t, d)
[0;1;32m                       ^
[0mIn file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
In file included from ../../base/allocator/partition_allocator/partition_root.h:52:
In file included from ../../base/allocator/partition_allocator/partition_direct_map_extent.h:10:
[1m../../base/allocator/partition_allocator/partition_page.h:367:15: [0m[0;1;31merror: [0m[1mstatic_assert expression is not an integral constant expression[0m
static_assert(offsetof(PartitionPage<ThreadSafe>, subsequent_page_metadata) ==
[0;1;32m              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m/usr/lib/llvm/13/bin/../../../../lib/clang/13.0.0/include/stddef.h:104:24: [0m[0;1;30mnote: [0mexpanded from macro 'offsetof'[0m
#define offsetof(t, d) __builtin_offsetof(t, d)
[0;1;32m                       ^
[0mIn file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
[1m../../base/allocator/partition_allocator/partition_root.h:927:25: [0m[0;1;31merror: [0m[1mno member named 'marked_full' in 'base::internal::SlotSpanMetadata<true>'[0m
  PA_DCHECK(!slot_span->marked_full);
[0;1;32m             ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_alloc_check.h:48:56: [0m[0;1;30mnote: [0mexpanded from macro 'PA_DCHECK'[0m
#define PA_DCHECK(condition) EAT_CHECK_STREAM_PARAMS(!(condition))
[0;1;32m                                                       ^~~~~~~~~
[0m[1m../../base/check.h:61:35: [0m[0;1;30mnote: [0mexpanded from macro 'EAT_CHECK_STREAM_PARAMS'[0m
       : ::logging::VoidifyStream(expr) & (*::logging::g_swallow_stream)
[0;1;32m                                  ^~~~
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1690:10: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::AllocFromBucket' requested here[0m
  return AllocFromBucket(bucket, flags, raw_size, slot_span_alignment,
[0;1;32m         ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1565:11: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::RawAlloc' requested here[0m
          RawAlloc(buckets + bucket_index, flags, raw_size, slot_span_alignment,
[0;1;32m          ^
[0m[1m../../base/allocator/partition_allocator/starscan/metadata_allocator.h:59:38: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::AllocFlagsNoHooks' requested here[0m
    return PCScanMetadataAllocator().AllocFlagsNoHooks(0, size,
[0;1;32m                                     ^
[0mIn file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
[1m../../base/allocator/partition_allocator/partition_root.h:930:46: [0m[0;1;31merror: [0m[1mno member named 'get_freelist_head' in 'base::internal::SlotSpanMetadata<true>'[0m
      reinterpret_cast<uintptr_t>(slot_span->get_freelist_head());
[0;1;32m                                  ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:970:24: [0m[0;1;31merror: [0m[1mno member named 'GetUtilizedSlotSize' in 'base::internal::SlotSpanMetadata<true>'[0m
  PA_DCHECK(slot_span->GetUtilizedSlotSize() <= slot_span->bucket->slot_size);
[0;1;32m            ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_alloc_check.h:48:56: [0m[0;1;30mnote: [0mexpanded from macro 'PA_DCHECK'[0m
#define PA_DCHECK(condition) EAT_CHECK_STREAM_PARAMS(!(condition))
[0;1;32m                                                       ^~~~~~~~~
[0m[1m../../base/check.h:61:35: [0m[0;1;30mnote: [0mexpanded from macro 'EAT_CHECK_STREAM_PARAMS'[0m
       : ::logging::VoidifyStream(expr) & (*::logging::g_swallow_stream)
[0;1;32m                                  ^~~~
[0mIn file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
[1m../../base/allocator/partition_allocator/partition_root.h:971:47: [0m[0;1;31merror: [0m[1mno member named 'GetSlotSizeForBookkeeping' in 'base::internal::SlotSpanMetadata<true>'[0m
  total_size_of_allocated_bytes += slot_span->GetSlotSizeForBookkeeping();
[0;1;32m                                   ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1186:24: [0m[0;1;31merror: [0m[1mno member named 'GetSlotSizeForBookkeeping' in 'base::internal::SlotSpanMetadata<true>'[0m
            slot_span->GetSlotSizeForBookkeeping());
[0;1;32m            ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_alloc_check.h:48:56: [0m[0;1;30mnote: [0mexpanded from macro 'PA_DCHECK'[0m
#define PA_DCHECK(condition) EAT_CHECK_STREAM_PARAMS(!(condition))
[0;1;32m                                                       ^~~~~~~~~
[0m[1m../../base/check.h:61:35: [0m[0;1;30mnote: [0mexpanded from macro 'EAT_CHECK_STREAM_PARAMS'[0m
       : ::logging::VoidifyStream(expr) & (*::logging::g_swallow_stream)
[0;1;32m                                  ^~~~
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1233:3: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::FreeInSlotSpan' requested here[0m
  FreeInSlotSpan(slot_start, slot_span);
[0;1;32m  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1273:3: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::RawFree' requested here[0m
  RawFree(slot_start, slot_span);
[0;1;32m  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1176:3: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::RawFreeWithThreadCache' requested here[0m
  RawFreeWithThreadCache(slot_start, slot_span);
[0;1;32m  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1075:9: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::FreeNoHooksImmediate' requested here[0m
  root->FreeNoHooksImmediate(address, slot_span, slot_start);
[0;1;32m        ^
[0m[1m../../base/allocator/partition_allocator/starscan/metadata_allocator.h:63:31: [0m[0;1;30mnote: [0min instantiation of member function 'base::PartitionRoot<true>::FreeNoHooks' requested here[0m
    PCScanMetadataAllocator().FreeNoHooks(ptr);
[0;1;32m                              ^
[0mIn file included from ../../base/memory/nonscannable_memory.cc:5:
In file included from ../../base/memory/nonscannable_memory.h:18:
In file included from ../../base/allocator/partition_allocator/partition_alloc.h:10:
[1m../../base/allocator/partition_allocator/partition_root.h:1187:47: [0m[0;1;31merror: [0m[1mno member named 'GetSlotSizeForBookkeeping' in 'base::internal::SlotSpanMetadata<true>'[0m
  total_size_of_allocated_bytes -= slot_span->GetSlotSizeForBookkeeping();
[0;1;32m                                   ~~~~~~~~~  ^
[0m[1m../../base/allocator/partition_allocator/partition_root.h:1188:21: [0m[0;1;31merror: [0m[1mno member named 'Free' in 'base::internal::SlotSpanMetadata<true>'[0m
  return slot_span->Free(slot_start);
[0;1;32m         ~~~~~~~~~  ^
[0m10 errors generated.
```

### CODE REVIEW

**Comment by PF4Public** [comment]
O.o Wow I didn't have any of those while building on x86_64

**Comment by darkbasic** [comment]
I'm closing because I've got a working v100 and I'll drop v99.

**Comment by PF4Public** [comment]
Did you use upstream Gentoo patches? Would you like to actualise v100 and electron-18?

**Comment by darkbasic** [comment]
ppc64 support has been upstreamed in the Gentoo repo (even if yet not keyworded), thanks to Stephan Hartmann.
I'll open a new PR for v100 and electron-18 soon.

**Pull request closed without merging**
