### PR TITLE
net-im/element-desktop: enable py3.12

### PR DESCRIPTION
**Pull request by joecool1029**
Ok lets try this again... I enabled it for 9999 as well.

### CODE REVIEW

**Comment by PF4Public** [comment]
Awesome! Thanks for taking care of it!

**Comment by joecool1029** [comment]
> Awesome! Thanks for taking care of it!

No problem, onto figuring out why element-web stopped building online. 😅

**Comment by PF4Public** [comment]
> No problem, onto figuring out why element-web stopped building online. 😅

Worksforme :) https://github.com/PF4Public/gentoo-overlay/actions/runs/9192149735

**Comment by joecool1029** [comment]
Weird, here's my failure log: 
[build.log](https://github.com/PF4Public/gentoo-overlay/files/15424470/build.log)

**Comment by PF4Public** [comment]
Maybe your version of yarn misbehaving?

**Comment by joecool1029** [comment]
> Maybe your version of yarn misbehaving?

@PF4Public It took me a few days but it's actually a kernel bug that affects all 6.9 versions released til now (6.9.0-6.9.2) . It can be worked around with exporting UV_USE_IO_URING=0 

https://github.com/nodejs/node/issues/53051

kernel fix should make it into 6.9.3, linus's tree has it https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=483a351ed4d464265aed61cab4a990b0023f8400

**Comment by PF4Public** [comment]
> a kernel bug that affects all 6.9 versions released til now (6.9.0-6.9.2)

Wow, it is not even in portage, you're living dangerously :D

**Pull request merged**
