### PR TITLE
www-client/ungoogled-chromium-bin: add alsa support

### PR DESCRIPTION
**Pull request by yukarigap**
This adds ALSA support with media-sound/apulse

### CODE REVIEW

**Comment by PF4Public** [comment]
Are you certain that adding `apulselib=…` in `src_install()` will allow it to use alsa? Have you tried it and was it functional? Just wanting to confirm before merging.

Could you please also maintain the status quo by not adding `+alsa` by default?

**Comment by yukarigap** [comment]
I tried it, the audio output worked as intended and there are no issues.

I'll make changes to the ebuild soon and do more testing.

**Comment by yukarigap** [comment]
The audio still works for the modified commit.

**Comment by PF4Public** [comment]
Honestly I meant to add alsa flag, but not enforce it by default with `+alsa`, but this way it is even better: the fewer flags, the better. :)

I'm looking through firefox ebuild and they seem to be doing this:
```
	pulseaudio? (
		|| (
			media-sound/pulseaudio
			>=media-sound/apulse-0.1.9
		)
	)
```
Wouldn't it be better this way?

I also think, that we may avoid mentioning `pulseaudio` in metadata.xml as it is a global flag.

Given that this is such a simple change, I'll consider adding it into non-binary ebuild.

**Comment by yukarigap** [comment]
> I'm looking through firefox ebuild and they seem to be doing this:
> 
> ```
> 	pulseaudio? (
> 		|| (
> 			media-sound/pulseaudio
> 			>=media-sound/apulse-0.1.9
> 		)
> 	)
> ```
> 
> Wouldn't it be better this way? And if that's true, we may even omit adding a new flag into ebuild, it would suffice to write like this:
> 
> ```
> || (
> 	media-sound/pulseaudio
> 	>=media-sound/apulse-0.1.9
> )
> ```
I tried those and they didn't pull in apulse. This pulls in apulse instead:

```
        pulseaudio? ( media-sound/pulseaudio )
        !pulseaudio? ( media-sound/apulse )
```

 I'll remove pulseaudio info from metadata.xml.

**Comment by PF4Public** [comment]
> I tried those and they didn't pull in apulse. This pulls in apulse instead:

Ofcourse! This should pull in `pulseaudio` by default (as it is the first one in a list) and if that is absent on your system, it will use `apulse` instead. Give it a try. You could try `emerge -v1 ungoogled-chromium-bin apulse` and see if it pulls in `pulseaudio`. (It shouldn't)

I hesistate making it `pulseaudio?` or `!pulseaudio?` given that "apulse" is providing an API completely compatible with `pulseaudio`, being essentially a drop-in replacement (if I understand it right) for it. An application should "feel" no difference whether there is `apulse` or `pulseaudio` itself, so I believe, those cannot be contradicting each other, it should be a matter of user choice. Am I wrong?

**Comment by yukarigap** [comment]
It worked.

**Comment by PF4Public** [comment]
@yukarigap I assume, that it works now without the need for a special treatment of a `pulseaudio` flag, right?

**Comment by mahdi1234** [comment]
Tried with https://github.com/yukarigap/gentoo-overlay/raw/master/www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-85.0.4183.102_p1.ebuild in local overlay, but it throws this error upon start

```
$ chromium-browser 
chromium-browser: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory

```

**Comment by PF4Public** [comment]
@mahdi1234 which files are installed by `apulse`? `equery f apulse` Should it be installing `libpulse.so`?

**Comment by mahdi1234** [comment]
Here's the files:
```
equery f apulse
 * Searching for apulse ...
 * Contents of media-sound/apulse-0.1.12_p20180803:
/usr
/usr/bin
/usr/bin/apulse
/usr/bin/i686-pc-linux-gnu-apulse
/usr/bin/x86_64-pc-linux-gnu-apulse
/usr/lib
/usr/lib/apulse
/usr/lib/apulse/libpulse-mainloop-glib.so -> libpulse-mainloop-glib.so.0
/usr/lib/apulse/libpulse-mainloop-glib.so.0
/usr/lib/apulse/libpulse-simple.so -> libpulse-simple.so.0
/usr/lib/apulse/libpulse-simple.so.0
/usr/lib/apulse/libpulse.so -> libpulse.so.0
/usr/lib/apulse/libpulse.so.0
/usr/lib64
/usr/lib64/apulse
/usr/lib64/apulse/libpulse-mainloop-glib.so -> libpulse-mainloop-glib.so.0
/usr/lib64/apulse/libpulse-mainloop-glib.so.0
/usr/lib64/apulse/libpulse-simple.so -> libpulse-simple.so.0
/usr/lib64/apulse/libpulse-simple.so.0
/usr/lib64/apulse/libpulse.so -> libpulse.so.0
/usr/lib64/apulse/libpulse.so.0
/usr/share
/usr/share/doc
/usr/share/doc/apulse-0.1.12_p20180803
/usr/share/doc/apulse-0.1.12_p20180803/README.md.bz2
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/apulse.1.bz2

```

**Comment by PF4Public** [comment]
>it apparently doesn't look into apulse dir

In firefox ebuild there is also this:

```sh
		apulselib="${EPREFIX%/}/usr/$(get_libdir)/apulse"
		patchelf --set-rpath "${apulselib}" "${ED%/}"${MOZILLA_FIVE_HOME}/libxul.so || die
```

Could it be that we also need to patch rpath?

**Comment by mahdi1234** [comment]
See my (edited, sorry for that) comment above following helped - 

`/usr/lib64 # ln -s /usr/lib64/apulse/libpulse.so.0 `

**Comment by yukarigap** [comment]
> @yukarigap I assume, that it works now without the need for a special treatment of a `pulseaudio` flag, right?

Yeah, it worked for me. Didn't expect for someone to have issues with apulse though.

**Comment by PF4Public** [comment]
@yukarigap Didn't you encounter the same issue with chromium binary unable to find the library? Did you do a symlink manually?

I also see this in firefox ebuild:
```sh
        # if the apulse libs are available in MOZILLA_FIVE_HOME then apulse
	# doesn't need to be forced into the LD_LIBRARY_PATH
	if use pulseaudio && has_version ">=media-sound/apulse-0.1.9" ; then
		einfo "APULSE found - Generating library symlinks for sound support"
		local lib
		pushd "${ED}"${MOZILLA_FIVE_HOME} &>/dev/null || die
		for lib in ../apulse/libpulse{.so{,.0},-simple.so{,.0}} ; do
			# a quickpkg rolled by hand will grab symlinks as part of the package,
			# so we need to avoid creating them if they already exist.
			if [[ ! -L ${lib##*/} ]] ; then
				ln -s "${lib}" ${lib##*/} || die
			fi
		done
		popd &>/dev/null || die
	fi
```
Looks like we also may attempt in a similar way to create the needed symlinks either into `/usr/$(get_libdir)/chromium-browser` or into `/usr/$(get_libdir)`

**Comment by yukarigap** [comment]
> @yukarigap Didn't you encounter the same issue with chromium binary unable to find the library? Did you do a symlink manually?
> 
> I also see this in firefox ebuild:
> 
> ```shell
>         # if the apulse libs are available in MOZILLA_FIVE_HOME then apulse
> 	# doesn't need to be forced into the LD_LIBRARY_PATH
> 	if use pulseaudio && has_version ">=media-sound/apulse-0.1.9" ; then
> 		einfo "APULSE found - Generating library symlinks for sound support"
> 		local lib
> 		pushd "${ED}"${MOZILLA_FIVE_HOME} &>/dev/null || die
> 		for lib in ../apulse/libpulse{.so{,.0},-simple.so{,.0}} ; do
> 			# a quickpkg rolled by hand will grab symlinks as part of the package,
> 			# so we need to avoid creating them if they already exist.
> 			if [[ ! -L ${lib##*/} ]] ; then
> 				ln -s "${lib}" ${lib##*/} || die
> 			fi
> 		done
> 		popd &>/dev/null || die
> 	fi
> ```
> 
> Looks like we also may attempt in a similar way to create the needed symlinks either into `/opt/chromium-browser` or into `/usr/$(get_libdir)`

Didn't realize I had an AppImage, removed it and I am getting the error: `chromium-browser: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory` when launching the real ungoogled-chromium.

**Comment by PF4Public** [comment]
> chromium-browser: error while loading shared libraries: libpulse.so.0: cannot open shared object file: No such file or directory

That is exactly, what was happening to **mahdi1234**. Browser expects to find `libpulse.so.0` in its usual place: `/usr/$(get_libdir)`, but apulse places it into `/usr/$(get_libdir)/apulse`. This means that it is necessary either to patch the rpath of a binary so that it could find the library in another folder, or make symlinks into `/usr/$(get_libdir)`, like **mahdi1234** had done.

IMHO the first one (patching rpath) is the proper way of fixing this, but unfortunately I don't have a system with apulse to test, so someone needs to do this in order to complete this PR.

I may only suggest something like this:

```sh
if  has_version ">=media-sound/apulse-0.1.9" ; then
    apulselib="${EPREFIX%/}/usr/$(get_libdir)/apulse"
    patchelf --set-rpath "${apulselib}" /opt/chromium-browser/chrome || die
fi
```

**Comment by mahdi1234** [comment]
I can try it, but not sure where to add it exactly? Did after `readme.gentoo_create_doc` line but it threw this violation

```
>>> Install www-client/ungoogled-chromium-bin-85.0.4183.102_p1 into /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/image
/var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work
 * ACCESS DENIED:  open_wr:      /opt/chromium-browser/chrome
patchelf: open: Permission denied
 * ERROR: www-client/ungoogled-chromium-bin-85.0.4183.102_p1::x-portage failed (install phase):

```

**Comment by mahdi1234** [comment]
Tried in `pkg_postinst()` but after that app segfaults

```
$ chromium-browser 
Segmentation fault
```

**Comment by PF4Public** [comment]
Oh, how unfortunate… and at the same time quite logical. I should have known better what rpath patching involves before suggesting this.

I've just looked into apulse repository and, it has a [Usage](https://github.com/i-rinat/apulse#usage) paragraph, which says that one should simply use `apulse` wrapper before a binary. So, if you do not patch the binary and create extra symlinks, you simply do `apulse chromium-browser`, which should work. And if this works, we need something like this at the end of `src_install()`:
```sh
if  has_version ">=media-sound/apulse-0.1.9" ; then
   sed -i 's/exec -a/exec -a apulse/' /opt/chromium-browser/chromium-launcher.sh
fi
```

**Comment by mahdi1234** [comment]
I confirm `apulse chromium-browser` works fine and sound is ok as well. Let me know if you have some ebuild or what exactly change and I can try it as well.

**Comment by PF4Public** [comment]
> what exactly change and I can try it as well.

I have already written above

**Comment by mahdi1234** [comment]
Tried locally `sed -i 's/exec -a/exec -a apulse/' /opt/chromium-browser/chromium-launcher.sh` but browser then starts in endless loop, strace running in circles, this is how sh looks after applied

```
cat /opt/chromium-browser/chromium-launcher.sh | grep apulse
exec -a apulse "chromium-browser" "$PROGDIR/chrome" --extra-plugin-dir=/usr/lib64/nsbrowser/plugins ${CHROMIUM_FLAGS} "$@"

```

**Comment by PF4Public** [comment]
Maybe it needs apulse quoted like "chromium-browser", that follows?

**Comment by mahdi1234** [comment]
neither
exec -a "apulse" "chromium-browser" "$PROGDIR/chrome" --extra-plugin-dir=/usr/lib64/nsbrowser/plugins ${CHROMIUM_FLAGS} "$@"
nor
exec -a "apulse chromium-browser" "$PROGDIR/chrome" --extra-plugin-dir=/usr/lib64/nsbrowser/plugins ${CHROMIUM_FLAGS} "$@"
worked.

**Comment by PF4Public** [comment]
Please, try removing "-a", this is probably extra in this situation.

**Comment by mahdi1234** [comment]
Both work fine.

**Comment by PF4Public** [comment]
Then I would suggest @yukarigap adding this at the end of `src_install()`:

```sh
if  has_version ">=media-sound/apulse-0.1.9" ; then
   sed -i 's/exec -a "chromium-browser"/exec -a "chromium-browser" apulse/' /opt/chromium-browser/chromium-launcher.sh
fi
```

**Comment by yukarigap** [comment]
> Then I would suggest @yukarigap adding this at the end of `src_install()`:
> 
> ```shell
> if  has_version ">=media-sound/apulse-0.1.9" ; then
>    sed -i 's/exec -a "chromium-browser"/exec -a "chromium-browser" apulse/' /opt/chromium-browser/chromium-launcher.sh
> fi
> ```

@PF4Public I just added this in the ebuild, and I end up getting an error when attempting to emerge ungoogled-chromium-bin.

```
^[[32;01m * ^[[39;49;00mPackage:    www-client/ungoogled-chromium-bin-85.0.4183.102_p1
^[[32;01m * ^[[39;49;00mRepository: localrepo
^[[32;01m * ^[[39;49;00mMaintainer: pf4public@mail.ru
^[[32;01m * ^[[39;49;00mUpstream:   https://github.com/Eloston/ungoogled-chromium/issues
^[[32;01m * ^[[39;49;00mUSE:        abi_x86_64 amd64 elibc_glibc generic kernel_linux l10n_am l10n_ar l10n_bg l10n_bn l10n_ca l10n_cs l10n_da l10n_de l10n_el l10n_en-GB l10n_es l10n_es-419 l10n_et l10n_fa l10n_fi l10n_fil l10>
^[[32;01m * ^[[39;49;00mFEATURES:   ccache network-sandbox preserve-libs sandbox userpriv usersandbox
 ^[[32;01m*^[[0m Determining the location of the kernel source code
 ^[[32;01m*^[[0m Found kernel source directory:
 ^[[32;01m*^[[0m     /usr/src/linux
 ^[[32;01m*^[[0m Found sources for kernel version:
 ^[[32;01m*^[[0m     5.4.60-gentoo
>>> Unpacking source...
>>> Unpacking ungoogled-chromium-bin-85.0.4183.102_p1-x86-64.tar.bz2 to /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work
>>> Source unpacked in /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work
>>> Preparing source in /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work ...
>>> Source compiled.
>>> Test phase [not enabled]: www-client/ungoogled-chromium-bin-85.0.4183.102_p1

>>> Install www-client/ungoogled-chromium-bin-85.0.4183.102_p1 into /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/image
/var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/work
 ^[[31;01m*^[[0m ^[[31;01mACCESS DENIED^[[0m:  mkostemp:     /opt/chromium-browser/sedXXXXXX
sed: couldn't open temporary file /opt/chromium-browser/sedXXXXXX: Permission denied
>>> Completed installing www-client/ungoogled-chromium-bin-85.0.4183.102_p1 into /var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/image

 ^[[32;01m*^[[0m Final size of build directory: 255488 KiB (249.5 MiB)
 ^[[32;01m*^[[0m Final size of installed tree:  254952 KiB (248.9 MiB)

 ^[[31;01m*^[[0m --------------------------- ACCESS VIOLATION SUMMARY ---------------------------
 ^[[31;01m*^[[0m LOG FILE: "/var/tmp/portage/www-client/ungoogled-chromium-bin-85.0.4183.102_p1/temp/sandbox.log"
 ^[[31;01m*^[[0m
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: mkostemp
S: deny
P: /opt/chromium-browser/sedXXXXXX
A: /opt/chromium-browser/sedXXXXXX
R: /opt/chromium-browser/sedXXXXXX
C: sed -i s/exec -a "chromium-browser"/exec -a "chromium-browser" apulse/ /opt/chromium-browser/chromium-launcher.sh
 ^[[31;01m*^[[0m --------------------------------------------------------------------------------
```

**Comment by PF4Public** [comment]
Ok, fine, we are probably trying to play against the rules. Try adding this:
```sh
if  has_version ">=media-sound/apulse-0.1.9" ; then
   sed -i 's/exec -a "chromium-browser"/exec -a "chromium-browser" apulse/' ./usr/$(get_libdir)/chromium-browser/chromium-launcher.sh
fi
```
just before this:
https://github.com/PF4Public/gentoo-overlay/blob/314cab025ce351cc7a25985df0c772bcbdf66c73/www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-85.0.4183.102_p1.ebuild#L153

Hope this makes it work finally.

**Comment by yukarigap** [comment]
> Ok, fine, we are probably trying to play against the rules. Try adding this:
> 
> ```shell
> if  has_version ">=media-sound/apulse-0.1.9" ; then
>    sed -i 's/exec -a "chromium-browser"/exec -a "chromium-browser" apulse/' ./usr/$(get_libdir)/chromium-browser/chromium-launcher.sh
> fi
> ```
> 
> just before this:
> 
> https://github.com/PF4Public/gentoo-overlay/blob/314cab025ce351cc7a25985df0c772bcbdf66c73/www-client/ungoogled-chromium-bin/ungoogled-chromium-bin-85.0.4183.102_p1.ebuild#L153
> 
> Hope this makes it work at last.

This works for me.

**Comment by PF4Public** [comment]
> This works for me.

Does audio work now?

**Comment by yukarigap** [comment]
> > This works for me.
> 
> But does audio work now? :D

Yeah, the audio works for me. @mahdi1234 should test it out for himself though.

**Comment by mahdi1234** [comment]
@PF4Public @yukarigap Confirmed, made the same changes and audio works, cheers :)

**Comment by PF4Public** [comment]
I will merge this PR then.
Thanks @yukarigap, @mahdi1234

**Comment by mahdi1234** [comment]
Emerged from overlay and everything's fine, thanks!

**Pull request merged**
