### PR TITLE
Allow to build chromium-94 with system ffmpeg

### PR DESCRIPTION
**Pull request by gringus**
Patch borrowed from Arch folks to allow to build with system ffmpeg (version 4.4 or older). Currently it's not possible to build with anything newer (eg 9999). I'm still in process of testing this, but should report back soon.

### CODE REVIEW

**Comment by PF4Public** [comment]
Just FYI: you will need `>=media-libs/harfbuzz-2.9.0` and comment out `doins -r out/Release/MEIPreload`

**Comment by gringus** [comment]
Rebased and re-trying.

**Comment by gringus** [comment]
Built nicely and works fine.

**Comment by PF4Public** [comment]
Excellent

**Comment by gringus** [comment]
Or course Mr Burns ;-)

**Pull request merged**
