### PR TITLE
Add arm64/ppc64 fixes to ungoogled-chromium-92*

### PR DESCRIPTION
**Pull request by skrinakron**
This adds the PPC64LE and ARM64 compatibility fixes found in the Chromium 92 ebuild in the official Portage repo. Builds and runs without issues on my PPC64LE system; it does hit https://crbug.com/264818 but that appears to be caused by my open-source radeon driver rather than these tweaks.

### CODE REVIEW

**Comment by PF4Public** [comment]
I'm aware of upstream arm and ppc support, I'm just not certain whether anyone needs it with ungoogled-chromium.

**Comment by skrinakron** [comment]
That's okay; I can set this variant ebuild up in a repo of my own. I was hoping to avoid that sort of splintering and marginalization of packages for these platforms, but since they may indeed have relatively few users, it's a bit of a chicken-and-egg problem and that's a fair call to make.

Do you intend to give this further consideration or should I just close the PR?

**Comment by PF4Public** [comment]
> Do you intend to give this further consideration or should I just close the PR?

Well, I have neither arm nor ppc at my disposal, so I cannot verify my ebuilds on those architectures, but… But since those are now supported upstream, I may just rely on them doing the job. 

Your reply suggests that you might be (willing to?) using ungoogled-chromium on arm and/or ppc and if I that guess is  correct, I can definitely add that support in my ebuilds. That's not that difficult actually, I would only be unable to test them, so keep it in mind.

With respect to your exact question I can tell that this PR is lacking manifests of external files, so I would like not to merge it as is. Therefore I'd suggest closing it on the grounds that I promise adding arm and ppc later with the upcoming 93 version if you don't mind of-course.

**Comment by skrinakron** [comment]
Ah, true, forgot to update the manifest; I'd been emerging from a local overlay and so didn't notice. I updated it in my branch now just for completeness' sake.

I am running the ungoogled-chromium produced by this ebuild on PPC64LE, and I'd definitely be willing to test version bumps one way or another. As for not being able to test on these architectures, that's the case in the Portage tree as well – there's some pretty basic stuff where you still have to add keywords yourself and sort of test as you go, so that's not a (new) problem.

I was unaware the ppc64 support had been upstreamed. The [few](https://bugs.gentoo.org/show_bug.cgi?id=669748) [sources](https://wiki.raptorcs.com/wiki/Porting/Chromium_(New)) I've found have said it hasn't yet been done, and the only Portage chrome ebuild with a ppc64 keyword is still for version 92. But fair enough if upstream in this case is Portage. :smile:

I'm closing this PR according to the discussion above. I'm happy running the 92 version in my branch for now, and we can return to this once we see how the situation turns out with 93.

**Comment by PF4Public** [comment]
Indeed there is no ppc in chromium 93, so I've taken only arm support for now. If you happen to notice ppc in 93 earlier than me, feel free to create a PR.

**Comment by PF4Public** [comment]
@skrinakron In case you didn't notice: #134 might be of interest for you.

**Comment by skrinakron** [comment]
It is – thank you for mentioning it! Looks like I won't have to be patching my own ungoogled-chromium anymore.

**Comment by PF4Public** [comment]
You could probably maintain ppc64 support together.

**Pull request closed without merging**
